
struct MockData {

    static let theWireCast = [
        "Aimee",
        "Artis, Anton",
        "Asher, Jimmy",
        "Bailey, John",
        "Baker, Brian",
        "Barksdale, Avon",
        "Barksdale, Brianna",
        "Barksdale, D'Angelo",
        "Barlow, Frank",
        "Ben-Eleazer, Eton",
        "Bernard",
        "Bell, Russell",
        "Big Guy",
        "Big Roy",
        "Blocker, Wendell",
        "Bond, Rupert",
        "Bratton, Savino",
        "Brice, De'Londa",
        "Brice, Namond",
        "Brice, Roland",
        "Broadus, Preston",
        "Brown, Bobby",
        "Brother Mouzone",
        "Bubbles",
        "Burrell, Ervin",
        "Butchie",
        "Campbell, Nerese",
        "Cantrell, Walter",
        "Carcetti, Jen",
        "Carcetti, Thomas",
        "Carr, Malik",
        "Carver, Ellis",
        "Castor, Aaron",
        "Cheryl",
        "Chess",
        "Christeson",
        "Cole, Ray",
        "Colicchio, Anthony",
        "Colvin, Howard",
        "Country",
        "Cousins, Reginald",
        "Coxson, Nat",
        "Crutchfield, Michael",
        "D[edit]",
        "D'Agostino, Theresa",
        "Daniels, Cedric",
        "Daniels, Marla",
        "Dante",
        "Davis, R. Clayton",
        "Dawson, Zenobia",
        "The Deacon",
        "Dee-Dee",
        "Delores",
        "Demper, Steven",
        "DiBiago, Bruce",
        "DiPasquale, Gary",
        "Diggins, Claude",
        "Donette",
        "Donnie",
        "Donut",
        "Donnelly, Marcia",
        "Dozerman, Kenneth",
        "Fitzhugh, Terrance",
        "Fletcher, Mike",
        "Foerster, Raymond",
        "Frazier, Warren",
        "Frazier, Randall",
        "Freamon, Lester",
        "Frog",
        "Fruit",
        "Garrick, Lloyd",
        "Gerard",
        "Gerry",
        "Ghost",
        "Glekas, George",
        "Gray, Anthony",
        "The Greek",
        "Greggs, Shakima",
        "Gutierrez, Alma",
        "Hauk, Thomas",
        "Haynes, Augustus",
        "Hendrix, Ricardo",
        "Hilton, Marquis",
        "Holley, Vernon",
        "Hucklebuck",
        "Hungry Man",
        "Innes, Shardene",
        "Jamal",
        "Judkins, Crystal",
        "Justin McRae",
        "Johnson, Herbert De'Rodd",
        "Kenard",
        "Kimmy",
        "Klebanow, Thomas",
        "Koutris, Kristos",
        "Krawczyk, Andy",
        "La La",
        "Lamar",
        "Lambert",
        "Landsman, Jay",
        "Lee, Michael",
        "Lee, Raylene",
        "Levy, Maurice",
        "Little Big Roy",
        "Little Kevin",
        "Little Man",
        "Little, Omar",
        "Luxenberg, Steven",
        "Mahon, Patrick",
        "Malatov, Sergei",
        "Manigault, Aaron",
        "Manigault, Devar",
        "Marimow, Charles",
        "Massey, Caroline",
        "Maui",
        "McArdle, Mike",
        "McGinty, Shaun",
        "McNulty, Elena",
        "McNulty, Jimmy",
        "McNulty, Michael",
        "McNulty, Sean",
        "Mello, Dennis",
        "Mitchell, Tosha",
        "Moreland, Bunk",
        "Motley, Vernon",
        "Nathan, Ilene",
        "Norris, Ed",
        "O-Dog",
        "Old Face Andre",
        "Pakusa, Thomas",
        "Parenti, David",
        "Parker, Coleman",
        "Partlow, Chris",
        "Pearlman, Rhonda",
        "Pearson, Felicia",
        "Perkins, Eunetta",
        "Perry",
        "Phelan, Daniel",
        "Phelps, Tim",
        "Phil-Boy",
        "Polk, Augustus",
        "Price, Damien Lavelle",
        "Price, Jeff",
        "Pryzbylewski, Roland",
        "Rawls, William",
        "Reed, Bobby",
        "Renaldo",
        "Reese, Amanda",
        "Rico",
        "Ronnie Mo",
        "Royce, Clarence",
        "Russell, Beatrice",
        "Sampson, Grace",
        "Santangelo, Michael",
        "Sapper",
        "Sherrod",
        "Slim Charles",
        "Sobotka, Frank",
        "Sobotka, Joan",
        "Sobotka, Louis",
        "Sobotka, Nick",
        "Sobotka, Ziggy",
        "Spamanto, Johnny",
        "Spry, Jay",
        "Squeak",
        "Stanfield, Marlo",
        "Sterling",
        "Stewart, Joe",
        "Stokes, Albert",
        "Sydnor, Leander",
        "Tank",
        "Taylor, Marvin",
        "Templeton, Scott",
        "Tilghman, Dwight",
        "Torret",
        "Twigg, Roger",
        "Tyson, Darnell",
        "Valchek, Stanislaus",
        "Vinson",
        "Vondopoulos, Spiros",
        "Wagstaff, Calvin",
        "Wagstaff, Randy",
        "Wallace",
        "Walker, Eddie",
        "Walon",
        "Watkins, Odell",
        "Weeks, Johnny",
        "Weems, Duquan",
        "Whiting, James",
        "Williams, Karim",
        "Williamson, Kintel",
        "Wilson, Norman",
        "Wise, Dennis",
        "Withers, Claudell",
        "Wright, Brandon"
    ]
}
